In [20]:
#persiapan
import pandas as pd
import numpy as np

# visualisasi
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# statistik
from scipy import stats

#import streamlit
import streamlit as st

## Load dataset clean

In [21]:
df_clean = pd.read_csv(
    "real_estate_clean.csv"
)

In [22]:
5 * 6

30

### Merapikan file : kolom, format tanggal

In [23]:
# rapikan nama kolom

df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.replace(" ", "_")
    .str.lower()
)

df_clean.columns

Index(['serial_number', 'list_year', 'date_recorded', 'town', 'address',
       'assessed_value', 'sale_amount', 'sales_ratio', 'property_type',
       'residential_type', 'non_use_code', 'location', 'year', 'month'],
      dtype='str')

In [24]:
df_clean["date_recorded"] = pd.to_datetime(
    df_clean["date_recorded"]
)

In [25]:
df_clean.head()

,serial_number,list_year,date_recorded,town,address,assessed_value,sale_amount,sales_ratio,property_type,residential_type,non_use_code,location,year,month
0,2020177,2020,2021-04-14,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,NaN,POINT (-73.06822 41.35014),2021.0,4.0
1,2020225,2020,2021-05-26,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN,2021.0,5.0
2,2020090,2020,2020-12-14,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN,2020.0,12.0
3,210288,2021,2022-06-20,Avon,12 BYRON DRIVE,179990.0,362500.0,0.4965,Residential,Condo,NaN,POINT (-72.879115982 41.773452988),2022.0,6.0
4,200500,2020,2021-09-07,Avon,245 NEW ROAD,217640.0,400000.0,0.5441,Residential,Single Family,NaN,NaN,2021.0,9.0

### Periksa dataset ulang

In [26]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 699240 entries, 0 to 699239
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   serial_number     699240 non-null  int64
 1   list_year         699240 non-null  int64
 2   date_recorded     699240 non-null  datetime64[us]
 3   town              699240 non-null  str
 4   address           699236 non-null  str
 5   assessed_value    699240 non-null  float64
 6   sale_amount       699240 non-null  float64
 7   sales_ratio       699240 non-null  float64
 8   property_type     699240 non-null  str
 9   residential_type  699240 non-null  str
 10  non_use_code      201279 non-null  str
 11  location          214091 non-null  str
 12  year              699240 non-null  float64
 13  month             699240 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(2), str(6)
memory usage: 115.3 MB

In [27]:
df_clean.describe()

,serial_number,list_year,date_recorded,assessed_value,sale_amount,sales_ratio,year,month
count,6.992400e+05,699240.000000,699240,6.992400e+05,6.992400e+05,6.992400e+05,699240.000000,699240.000000
mean,7.484256e+05,2014.717728,2015-12-28 07:45:11.584005,2.523573e+05,3.757951e+05,5.010083e+00,2015.461501,6.869095
min,2.100000e+01,2006.000000,1999-04-05 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,1999.000000,1.000000
25%,7.093175e+04,2011.000000,2011-10-05 00:00:00,1.106000e+05,1.570000e+05,5.536000e-01,2011.000000,4.000000
50%,1.404660e+05,2015.000000,2016-07-19 00:00:00,1.599000e+05,2.459000e+05,6.675000e-01,2016.000000,7.000000
75%,1.904870e+05,2019.000000,2020-05-29 00:00:00,2.481000e+05,3.860000e+05,8.136000e-01,2020.000000,10.000000
max,2.000500e+09,2022.000000,2023-09-29 00:00:00,8.815100e+08,3.187900e+08,1.226420e+06,2023.000000,12.000000
std,8.959386e+06,4.906458,NaN,1.280857e+06,9.232946e+05,1.680233e+03,4.922560,3.235183

### Check ulang missing value nya

In [28]:
df_clean.isnull().sum()

serial_number            0
list_year                0
date_recorded            0
town                     0
address                  4
assessed_value           0
sale_amount              0
sales_ratio              0
property_type            0
residential_type         0
non_use_code        497961
location            485149
year                     0
month                    0
dtype: int64

### Copy data untuk ke visualisasi

In [29]:
df_viz = df_clean.copy()

In [30]:
### Histogram / scatter

In [31]:
cap = df_viz["sale_amount"].quantile(0.95)

df_viz = df_viz[
    df_viz["sale_amount"] <= cap
]

### Median Sale per year

In [32]:
# median sale amount per year

yearly_trend = (
    df_clean
    .groupby("year")["sale_amount"]
    .median()
    .reset_index()
)

yearly_trend

      year  sale_amount
0   1999.0      95000.0
1   2001.0     425855.5
2   2003.0     158900.0
3   2004.0     286900.0
4   2005.0     150000.0
5   2006.0     260000.0
6   2007.0     270000.0
7   2008.0     240000.0
8   2009.0     215000.0
9   2010.0     222100.0
10  2011.0     210000.0
11  2012.0     220000.0
12  2013.0     220500.0
13  2014.0     210000.0
14  2015.0     214000.0
15  2016.0     215000.0
16  2017.0     227000.0
17  2018.0     225000.0
18  2019.0     230000.0
19  2020.0     270000.0
20  2021.0     295000.0
21  2022.0     320000.0
22  2023.0     332300.0